server.port=8085
spring.application.name=auth-service

# Connect to the Shared Database Instance
spring.datasource.url=jdbc:postgresql://localhost:5431/auth_db
spring.datasource.username=ptechie
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
# JWT Configuration
jwt.secret=${JWT_SECRET:mysecretkey123456789012345678901234567890}
jwt.expiration=86400000
eureka.instance.prefer-ip-address=true
