export const CATEGORY_NAMES = [
  'Smart Watches',
  'Headphones',
  'Smart Phones',
  'Laptops',
  'Gaming Console',
  'Tablets',
];

export const CATEGORIES = ['All', ...CATEGORY_NAMES];

export const CATEGORY_ALIASES = {
  iPhone: 'Smart Phones',
  Android: 'Smart Phones',
  Mac: 'Laptops',
  iPad: 'Tablets',
  Watch: 'Smart Watches',
  Audio: 'Headphones',
  Accessories: 'Gaming Console',
  Other: 'Gaming Console',
  'Tat ca': 'All',
  'Phu kien': 'Gaming Console',
  Khac: 'Gaming Console',
};

export const PRODUCT_CATALOG = [
  {
    skuCode: 'chrome_watch',
    name: 'Chrome Watch',
    description: 'Polished smartwatch with AMOLED display, health tracking, and all-day battery life.',
    price: 9690000,
    category: 'Smart Watches',
    imageUrl: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=1000&auto=format&fit=crop',
    stockQuantity: 32,
    brand: 'KDK',
    color: 'Silver',
    rating: 4.5,
    salePercent: 0,
    tag: 'Exclusive',
  },
  {
    skuCode: 'black_sports_watch',
    name: 'Black Sports Watch',
    description: 'Rugged fitness watch with GPS, swim tracking, sleep insights, and quick-charge battery.',
    price: 8990000,
    category: 'Smart Watches',
    imageUrl: 'https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=1000&auto=format&fit=crop',
    stockQuantity: 26,
    brand: 'KDK',
    color: 'Black',
    rating: 4.6,
    salePercent: 20,
    tag: 'Hot sale',
  },
  {
    skuCode: 'apple_watch_ultra_2',
    name: 'Apple Watch Ultra 2',
    description: 'Titanium smartwatch with precision GPS, bright display, and endurance sports features.',
    price: 21990000,
    category: 'Smart Watches',
    imageUrl: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=1000&auto=format&fit=crop',
    stockQuantity: 18,
    brand: 'Apple',
    color: 'Titanium',
    rating: 4.8,
    salePercent: 6,
    tag: 'Premium',
  },
  {
    skuCode: 'playstation_headset',
    name: 'PlayStation Headset',
    description: 'Wireless gaming headset with low-latency audio, plush earcups, and clear voice chat.',
    price: 5990000,
    category: 'Headphones',
    imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=1000&auto=format&fit=crop',
    stockQuantity: 24,
    brand: 'Sony',
    color: 'White',
    rating: 4.5,
    salePercent: 0,
    tag: 'Gaming',
  },
  {
    skuCode: 'sony_wh1000xm5',
    name: 'Sony WH-1000XM5',
    description: 'Flagship noise cancelling headphones with 30-hour battery and multipoint connection.',
    price: 8990000,
    category: 'Headphones',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop',
    stockQuantity: 36,
    brand: 'Sony',
    color: 'Black',
    rating: 4.7,
    salePercent: 10,
    tag: 'Noise cancel',
  },
  {
    skuCode: 'airpods_max',
    name: 'AirPods Max',
    description: 'Over-ear Apple headphones with spatial audio, active noise cancellation, and premium build.',
    price: 12990000,
    category: 'Headphones',
    imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=1000&auto=format&fit=crop',
    stockQuantity: 20,
    brand: 'Apple',
    color: 'Silver',
    rating: 4.7,
    salePercent: 7,
    tag: 'Spatial audio',
  },
  {
    skuCode: 'iphone_14_pro',
    name: 'iPhone 14 Pro',
    description: 'A16 chip, Dynamic Island, 48MP camera, and Always-On Super Retina display.',
    price: 19990000,
    category: 'Smart Phones',
    imageUrl: 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?w=1000&auto=format&fit=crop',
    stockQuantity: 28,
    brand: 'Apple',
    color: 'Black',
    rating: 4.7,
    salePercent: 6,
    tag: '5G',
  },
  {
    skuCode: 'android_phone_premium_set',
    name: 'Android Phone Premium Set',
    description: 'Premium Android bundle with high-refresh display, AI camera tools, and fast charging.',
    price: 14990000,
    category: 'Smart Phones',
    imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1000&auto=format&fit=crop',
    stockQuantity: 34,
    brand: 'Google',
    color: 'White',
    rating: 4.6,
    salePercent: 0,
    tag: 'Combo',
  },
  {
    skuCode: 'samsung_s24_ultra',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Galaxy AI phone with integrated S Pen, 200MP camera, and Dynamic AMOLED display.',
    price: 31990000,
    category: 'Smart Phones',
    imageUrl: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=1000&auto=format&fit=crop',
    stockQuantity: 22,
    brand: 'Samsung',
    color: 'Titanium',
    rating: 4.8,
    salePercent: 5,
    tag: 'AI phone',
  },
  {
    skuCode: 'silver_laptop_pro',
    name: 'Silver Laptop Pro',
    description: 'Slim aluminum laptop with bright display, fast SSD, and reliable performance for work.',
    price: 27990000,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=1000&auto=format&fit=crop',
    stockQuantity: 16,
    brand: 'KDK',
    color: 'Silver',
    rating: 4.7,
    salePercent: 7,
    tag: 'Work ready',
  },
  {
    skuCode: 'macbook_air_15',
    name: 'MacBook Air 15',
    description: 'Large Liquid Retina display, silent Apple silicon performance, and long battery life.',
    price: 32990000,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1000&auto=format&fit=crop',
    stockQuantity: 14,
    brand: 'Apple',
    color: 'Silver',
    rating: 4.8,
    salePercent: 0,
    tag: 'Thin design',
  },
  {
    skuCode: 'dell_xps_15_oled',
    name: 'Dell XPS 15 OLED',
    description: 'Creator laptop with OLED display, dedicated graphics, and premium machined chassis.',
    price: 49990000,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=1000&auto=format&fit=crop',
    stockQuantity: 10,
    brand: 'Dell',
    color: 'Black',
    rating: 4.6,
    salePercent: 4,
    tag: 'Creator',
  },
  {
    skuCode: 'playstation_5',
    name: 'PlayStation 5',
    description: 'Next-gen console with ultra-fast SSD, DualSense controller, and 4K gaming support.',
    price: 13990000,
    category: 'Gaming Console',
    imageUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=1000&auto=format&fit=crop',
    stockQuantity: 15,
    brand: 'Sony',
    color: 'White',
    rating: 4.8,
    salePercent: 10,
    tag: 'Best seller',
  },
  {
    skuCode: 'xbox_series_x',
    name: 'Xbox Series X',
    description: 'Powerful console with fast load times, 4K gameplay, and a huge Game Pass library.',
    price: 12990000,
    category: 'Gaming Console',
    imageUrl: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=1000&auto=format&fit=crop',
    stockQuantity: 12,
    brand: 'Microsoft',
    color: 'Black',
    rating: 4.6,
    salePercent: 17,
    tag: 'Hot sale',
  },
  {
    skuCode: 'vr_gaming_headset',
    name: 'VR Gaming Headset',
    description: 'Immersive VR headset for games, virtual events, and interactive entertainment.',
    price: 16990000,
    category: 'Gaming Console',
    imageUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=1000&auto=format&fit=crop',
    stockQuantity: 19,
    brand: 'Meta',
    color: 'White',
    rating: 4.5,
    salePercent: 30,
    tag: 'Deal of day',
  },
  {
    skuCode: 'tablet_x5',
    name: 'Tablet X5',
    description: 'Portable tablet with vivid display, stylus support, and reliable battery for travel.',
    price: 15990000,
    category: 'Tablets',
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=1000&auto=format&fit=crop',
    stockQuantity: 27,
    brand: 'KDK',
    color: 'Silver',
    rating: 4.5,
    salePercent: 0,
    tag: 'Portable',
  },
  {
    skuCode: 'ipad_air',
    name: 'iPad Air',
    description: 'Light tablet with Apple silicon, vivid display, Touch ID, and Apple Pencil support.',
    price: 19990000,
    category: 'Tablets',
    imageUrl: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=1000&auto=format&fit=crop',
    stockQuantity: 21,
    brand: 'Apple',
    color: 'Blue',
    rating: 4.7,
    salePercent: 5,
    tag: 'Creative',
  },
  {
    skuCode: 'galaxy_tab_s9',
    name: 'Galaxy Tab S9',
    description: 'Premium Android tablet with AMOLED screen, S Pen, and water-resistant design.',
    price: 22990000,
    category: 'Tablets',
    imageUrl: 'https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?w=1000&auto=format&fit=crop',
    stockQuantity: 17,
    brand: 'Samsung',
    color: 'Graphite',
    rating: 4.6,
    salePercent: 8,
    tag: 'AMOLED',
  },
];

export const PRODUCT_META = PRODUCT_CATALOG.reduce((items, product) => ({
  ...items,
  [product.skuCode]: {
    brand: product.brand,
    color: product.color,
    rating: product.rating,
    salePercent: product.salePercent,
    tag: product.tag,
  },
}), {});

export const PRODUCT_BY_SKU = PRODUCT_CATALOG.reduce((items, product) => ({
  ...items,
  [product.skuCode]: product,
}), {});

export const BRANDS = ['All', 'Apple', 'Sony', 'Samsung', 'KDK', 'Dell', 'Meta', 'Microsoft', 'Google'];

export const COLORS = ['All', 'Black', 'Silver', 'White', 'Blue', 'Titanium', 'Graphite'];

export const PRICE_RANGES = [
  { id: 'all', label: 'All prices', min: 0, max: Number.POSITIVE_INFINITY },
  { id: 'under-10', label: 'Under 10,000,000 VND', min: 0, max: 10000000 },
  { id: '10-20', label: '10,000,000 - 20,000,000 VND', min: 10000000, max: 20000000 },
  { id: '20-35', label: '20,000,000 - 35,000,000 VND', min: 20000000, max: 35000000 },
  { id: 'over-35', label: 'Over 35,000,000 VND', min: 35000000, max: Number.POSITIVE_INFINITY },
];

export const QUICK_TAGS = ['5G', 'wifi', 'Game', 'combo', 'Silver', 'white'];

export const CATEGORY_TILES = [
  {
    name: 'Smart Watches',
    imageUrl: PRODUCT_BY_SKU.black_sports_watch.imageUrl,
    description: 'Fitness tracking, bright displays, and premium straps.',
  },
  {
    name: 'Headphones',
    imageUrl: PRODUCT_BY_SKU.sony_wh1000xm5.imageUrl,
    description: 'Noise cancellation and immersive wireless audio.',
  },
  {
    name: 'Smart Phones',
    imageUrl: PRODUCT_BY_SKU.iphone_14_pro.imageUrl,
    description: 'Flagship cameras, fast chips, and 5G connectivity.',
  },
  {
    name: 'Laptops',
    imageUrl: PRODUCT_BY_SKU.macbook_air_15.imageUrl,
    description: 'Portable machines for study, work, and creation.',
  },
  {
    name: 'Gaming Console',
    imageUrl: PRODUCT_BY_SKU.playstation_5.imageUrl,
    description: 'Consoles, VR, and gaming audio for every setup.',
  },
  {
    name: 'Tablets',
    imageUrl: PRODUCT_BY_SKU.tablet_x5.imageUrl,
    description: 'Big-screen entertainment, notes, and productivity.',
  },
];

export const FALLBACK_IMAGES = PRODUCT_CATALOG.map((product) => product.imageUrl);

