apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techshop-frontend
  name: techshop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techshop-frontend
  template:
    metadata:
      labels:
        app: techshop-frontend
    spec:
      containers:
        - image: microservices-tutorial/techshop-frontend:latest
          name: techshop-frontend
          ports:
            - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: techshop-frontend
  name: techshop-frontend
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: techshop-frontend
