server.port=8086
spring.application.name=chatbot-service
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
groq.api.key=${GROQ_API_KEY:}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model.name=llama-3.3-70b-versatile
product.service.url=http://product-service:8080/api/product
