apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-auth:5433/auth-service
            - name: JWT_SECRET
              value: TechShopJwtSecretKeyForHS512MustBeAtLeastSixtyFourBytesLong2026!
          image: microservices-tutorial/auth-service:latest
          name: auth-service
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-service
  name: auth-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    app: auth-service
